export const projects = [
  {
    title: 'Genie AI',
    description: "Landing page for a future big web app with artificial intelligence.",
      image: '/images/genieai.png',
      tags: ['Next.js', 'Framer motion'],
    source: 'https://www.genieai.eu/',
    visit: 'https://github.com/Villiss/genie_ai',
    id: 0,
  },
  // {
  //   title: 'Vilim Chat',
  //   description: "Simple Chat application. Feel free to chat with me. Credentials on github.",
  //     image: '/images/1.png',
  //     tags: ['React', 'ChatEngine'],
  //   source: 'https://vilimchat.netlify.app/',
  //   visit: 'https://github.com/Villiss/vilimchat',
  //   id: 0,
  // },
  // {
  //   title: 'Vilim shop',
  //   description:"Easy ecommerce project. Here are only few products, but the purpose of this ecommerce was to get in touch with React.js. Credentials on github.",
  //   image: '/images/2.png',
  //   tags: ['React', 'Stripe', 'Chec.io'],
  //   source: 'https://vilimshop.netlify.app/',
  //   visit: 'https://github.com/Villiss/vilimshop',
  //   id: 1,
  // },
  {
    title: 'TWU',
    description:"Small information website, basically TWU Portfolio of projects.",
    image: '/images/3.png',
    tags: ['React', 'Framer-motion'],
    source: 'https://www.twu.sk/',
    visit: 'https://github.com/Villiss/twu',
    id: 1,
  },
  {
    title: 'skladany.sk',
    description:"Information website with Gallery and Contact form for Skladany.sk - construction company",
    image: '/images/skladany.png',
    tags: ['React'],
    source: 'https://www.skladany.sk/',
    visit: 'https://github.com/Villiss/skladany',
    id: 2,
  },
  {
    title: 'mofito.eu',
    description:"Informational website for Mofito.",
    image: '/images/mofitoeu.png',
    tags: ['React'],
    source: 'https://www.mofito.eu/',
    visit: 'https://github.com/Villiss/mofitoeu',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Finished high school and started studium at the universtiy', },
  { year: 2019, text: 'Tried to code some tech startups with friends', },
  { year: 2020, text: 'Started to intesively study and code in technologies such as React and React Native', },
  { year: 2021, text: 'Landed my first developer job alongside school', },
  { year: 2022, text: 'Started as a freelancer developer - Cross platform mobile app developer', },
];